#!/usr/bin/env bash
set -euo pipefail

topics=(
  cli
  command-line
  command-line-tool
  terminal
  tui
  shell
  console
  commandline
)

star_windows=(
  '>1000'
  '500..1000'
  '250..500'
  '100..250'
  '50..100'
)

keywords=(
  cli
  command-line
  commandline
  command
  terminal
  shell
  console
  tui
  developer-tool
  devtool
  command-line-interface
  command-line-application
)

languages=(
  Rust
  Go
  Python
  Shell
  JavaScript
  TypeScript
  C
  C++
  Objective-C
  Java
  PHP
  Ruby
  Lua
  Zig
  Haskell
  Elixir
  Swift
  Kotlin
  Scala
  Clojure
  Perl
  R
  Dart
  OCaml
  Nim
)

cat <<'HEADER'
# GitHub repository-search partitions for the ranked CLI corpus seed.
#
# Generated by scripts/generate_cli_corpus_queries.sh.
# Keep these queries broad enough to find popular CLI/tool repos while preserving
# explicit provenance in corpus/cli-tools.seed.json.
HEADER

for topic in "${topics[@]}"; do
  for stars in "${star_windows[@]}"; do
    printf 'topic:%s stars:%s\n' "$topic" "$stars"
  done
done

for keyword in "${keywords[@]}"; do
  for stars in "${star_windows[@]}"; do
    printf '%s stars:%s\n' "$keyword" "$stars"
  done
done

for topic in "${topics[@]}"; do
  for language in "${languages[@]}"; do
    for stars in '>500' '100..500' '50..100'; do
      printf 'topic:%s language:%s stars:%s\n' "$topic" "$language" "$stars"
    done
  done
done
